package org.relaxer.framework.testScript.rTestScript;

/**
 * TestScriptFactory is generated by Relaxer based on testScript.rng.
 *
 * @version testScript.rng 1.0 (Mon Sep 29 12:19:25 JST 2003)
 * @author  Relaxer 1.0b (http://www.relaxer.org)
 */
public class TestScriptFactory {
    private static ITestScriptFactory factory;

    /**
     * Sets a factory.
     *
     * @param newFactory
     */
    public static void setFactory(ITestScriptFactory newFactory) {
        factory = newFactory;
    }

    /**
     * Gets the factory.
     *
     * @return ITestScriptFactory
     */
    public static ITestScriptFactory getFactory() {
        if (factory == null) {
            factory = new DefaultTestScriptFactory();
        }
        return (factory);
    }
}
