package com.AsamiOffice.jaba2.text.update.rRule;

import org.w3c.dom.*;

/**
 * DefaultRuleFactory is generated by Relaxer based on rule.rlx.
 *
 * @version rule.rlx (Thu Nov 09 13:17:43 JST 2000)
 * @author  Relaxer 0.11.1b (by ASAMI@Yokohama)
 */
public class DefaultRuleFactory extends AbstractRuleFactory {

    /**
     * Creates a default <code>RuleSet</code>.
     * This method is a hook method of the AbstractRuleFactory.
     *
     * @return RuleSet
     */
    public RuleSet createRuleSet() {
        return (new RuleSet());
    }

    /**
     * Creates a default <code>Rule</code>.
     * This method is a hook method of the AbstractRuleFactory.
     *
     * @return Rule
     */
    public Rule createRule() {
        return (new Rule());
    }

    /**
     * Creates a default <code>Replace</code>.
     * This method is a hook method of the AbstractRuleFactory.
     *
     * @return Replace
     */
    public Replace createReplace() {
        return (new Replace());
    }
}
