package com.AsamiOffice.jaba2.text.update.rRule;

/**
 * RuleFactory is generated by Relaxer based on rule.rlx.
 *
 * @version rule.rlx (Thu Nov 09 13:17:43 JST 2000)
 * @author  Relaxer 0.11.1b (by ASAMI@Yokohama)
 */
public class RuleFactory {
    private static IRuleFactory factory;

    /**
     * Sets a factory.
     *
     * @param newFactory
     */
    public static void setFactory(IRuleFactory newFactory) {
        factory = newFactory;
    }

    /**
     * Gets the factory.
     *
     * @return IRuleFactory
     */
    public static IRuleFactory getFactory() {
        if (factory == null) {
            factory = new DefaultRuleFactory();
        }
        return (factory);
    }
}
